-- Seed prerequisites with per-OS install commands (🍎 macOS + 🪟 Windows)
-- install_command is kept as a legacy fallback (mirrors the macOS command).
INSERT INTO public.prerequisites
    (module_number, video_number, install_name, install_command, install_command_macos, install_command_windows, verification_command)
VALUES
(1, 1, 'Google Cloud CLI',
    'brew install --cask google-cloud-sdk',
    'brew install --cask google-cloud-sdk',
    'winget install --id Google.CloudSDK -e',
    'gcloud version'),
(1, 1, 'Docker Desktop',
    'brew install --cask docker',
    'brew install --cask docker',
    'winget install --id Docker.DockerDesktop -e',
    'docker --version'),
(1, 2, 'Fly.io CLI',
    'brew install flyctl',
    'brew install flyctl',
    'pwsh -Command "iwr https://fly.io/install.ps1 -useb | iex"',
    'flyctl version'),
(1, 2, 'Supabase CLI',
    'brew install supabase/tap/supabase',
    'brew install supabase/tap/supabase',
    'scoop install supabase',
    'supabase --version'),
(2, 1, 'Node.js',
    'brew install node@20',
    'brew install node@20',
    'winget install --id OpenJS.NodeJS.LTS -e',
    'node -v && npm -v'),
(2, 2, 'Python 3.11',
    'brew install python@3.11',
    'brew install python@3.11',
    'winget install --id Python.Python.3.11 -e',
    'python3 --version');
