FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod .
RUN go mod download
COPY . .
RUN go build -o problem-server .

FROM alpine:3.19
WORKDIR /app
COPY --from=build /app/problem-server .
COPY templates/ templates/
EXPOSE 8080
CMD ["./problem-server"]
