-- Stores AI-generated infographic layouts and their course relations.
CREATE TABLE IF NOT EXISTS public.infographics (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    module_number    INT NOT NULL DEFAULT 1,
    video_number     INT NOT NULL DEFAULT 1,
    sentence_id      BIGINT REFERENCES public.sentences(id) ON DELETE SET NULL,
    topic            TEXT NOT NULL,
    style            TEXT NOT NULL,
    layout_json      JSONB NOT NULL,
    azure_blob_name  TEXT,
    status           TEXT DEFAULT 'generated' -- 'generated', 'saved_to_azure'
);

-- Enable RLS
ALTER TABLE public.infographics ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow public read access" ON public.infographics FOR SELECT USING (true);
CREATE POLICY "Allow public all access" ON public.infographics FOR ALL USING (true);
