-- Create infographics table
CREATE TABLE IF NOT EXISTS public.infographics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    module_number INT NOT NULL DEFAULT 1,
    video_number INT NOT NULL DEFAULT 1,
    sentence_id BIGINT, -- Optional relation to a specific script sentence
    topic TEXT NOT NULL,
    style TEXT NOT NULL,
    layout_json JSONB NOT NULL,
    azure_blob_name TEXT,
    status TEXT DEFAULT 'generated'
);

-- Enable RLS
ALTER TABLE public.infographics ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access" ON public.infographics
    FOR SELECT USING (true);

-- Allow public all access
CREATE POLICY "Allow public all access" ON public.infographics
    FOR ALL USING (true);
