-- Create generated_images table
CREATE TABLE IF NOT EXISTS public.generated_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    module_number INT NOT NULL DEFAULT 1,
    video_number INT NOT NULL DEFAULT 1,
    prompt TEXT NOT NULL,
    refined_prompt TEXT,
    image_url TEXT,
    azure_blob_name TEXT,
    status TEXT DEFAULT 'generated' -- 'generated', 'saved_to_azure'
);

-- Enable RLS
ALTER TABLE public.generated_images ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access" ON public.generated_images
    FOR SELECT USING (true);

-- Allow public all access
CREATE POLICY "Allow public all access" ON public.generated_images
    FOR ALL USING (true);
