-- Create certification_videos table
CREATE TABLE IF NOT EXISTS public.certification_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    module_number INT NOT NULL DEFAULT 1,
    video_number INT NOT NULL DEFAULT 1,
    title TEXT NOT NULL,
    description TEXT,
    edit_todo TEXT,
    embed_url TEXT NOT NULL,
    share_url TEXT NOT NULL
);

-- Enable RLS
ALTER TABLE public.certification_videos ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access" ON public.certification_videos
    FOR SELECT USING (true);

-- Allow public all access
CREATE POLICY "Allow public all access" ON public.certification_videos
    FOR ALL USING (true);
