-- =============================================================================
-- Migration: memory_palaces — one method-of-loci memory palace per module
-- Used by 5_Symbols/production/postprod/memory_palace.html
-- Run in Supabase SQL Editor:
-- https://supabase.com/dashboard/project/rmekfsdhglyiralxvkwc/sql/new
-- =============================================================================

-- A Memory Palace is a method-of-loci sketch generated from a module's full
-- script. Each module has at most one saved palace per user. The generated
-- structure (theme + rooms + loci) is stored as JSONB in `palace` so the page
-- can re-render the exact sketch it saved.

CREATE TABLE IF NOT EXISTS public.memory_palaces (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id   INTEGER NOT NULL,                 -- 1..5 (course module number)
    user_id     TEXT    NOT NULL DEFAULT 'default',
    theme       TEXT    DEFAULT '',               -- palace theme name, e.g. "The Glass Observatory"
    title       TEXT    DEFAULT '',               -- module title snapshot
    palace      JSONB   DEFAULT '{}'::jsonb,      -- { theme, rooms:[{ name, video, loci:[{ peg, concept, image }] }] }
    notes       TEXT    DEFAULT '',               -- free-text instructor notes / walk-through tweaks
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (module_id, user_id)
);

-- Enable RLS
ALTER TABLE public.memory_palaces ENABLE ROW LEVEL SECURITY;

-- Allow public read
DROP POLICY IF EXISTS "Public read memory_palaces" ON public.memory_palaces;
CREATE POLICY "Public read memory_palaces" ON public.memory_palaces
    FOR SELECT USING (true);

-- Allow public insert/update/delete (anon-key browser client)
DROP POLICY IF EXISTS "Public all memory_palaces" ON public.memory_palaces;
CREATE POLICY "Public all memory_palaces" ON public.memory_palaces
    FOR ALL USING (true) WITH CHECK (true);
