-- Migration: sentence_drawings table
-- Stores one hand-drawn / AI-generated Excalidraw diagram per sentence.
-- The editable scene lives in excalidraw_json (JSONB); a flattened PNG of the
-- same drawing is uploaded to Azure Blob Storage and referenced here by
-- azure_blob_name + image_url (same-origin proxy URL). Run in Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS sentence_drawings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sentence_id INTEGER NOT NULL REFERENCES sentences(id) ON DELETE CASCADE,
  module_number INTEGER NOT NULL DEFAULT 1,
  video_number INTEGER NOT NULL DEFAULT 1,
  excalidraw_json JSONB,
  azure_blob_name TEXT DEFAULT '',
  image_url TEXT DEFAULT '',
  prompt_used TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sentence_drawings_sentence ON sentence_drawings(sentence_id);
CREATE INDEX IF NOT EXISTS idx_sentence_drawings_module_video ON sentence_drawings(module_number, video_number);

-- One drawing per sentence; enables upsert via ON CONFLICT (sentence_id).
CREATE UNIQUE INDEX IF NOT EXISTS idx_sentence_drawings_one_per_sentence
  ON sentence_drawings(sentence_id);

ALTER TABLE sentence_drawings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS anon_select_sentence_drawings ON sentence_drawings;
CREATE POLICY anon_select_sentence_drawings ON sentence_drawings FOR SELECT USING (true);

DROP POLICY IF EXISTS anon_insert_sentence_drawings ON sentence_drawings;
CREATE POLICY anon_insert_sentence_drawings ON sentence_drawings FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS anon_update_sentence_drawings ON sentence_drawings;
CREATE POLICY anon_update_sentence_drawings ON sentence_drawings FOR UPDATE USING (true);

DROP POLICY IF EXISTS anon_delete_sentence_drawings ON sentence_drawings;
CREATE POLICY anon_delete_sentence_drawings ON sentence_drawings FOR DELETE USING (true);
