CREATE TABLE IF NOT EXISTS video_drawings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id BIGINT REFERENCES videos(id) ON DELETE CASCADE,
    excalidraw_json JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(video_id)
);

ALTER TABLE video_drawings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON video_drawings FOR SELECT USING (true);
CREATE POLICY "Enable all access for all users" ON video_drawings FOR ALL USING (true);
