-- ── DOMAIN-SPECIFIC LANGUAGE (DSL) DICTIONARY ──────────────────────────────
-- Interactive glossary of project terminology, framework terms, and concepts.
-- Each entry has: term, definition, context (where it's used), category,
-- related_terms, and examples.

CREATE TABLE IF NOT EXISTS public.dsl_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term TEXT NOT NULL UNIQUE,
    definition TEXT NOT NULL,
    context TEXT DEFAULT '',
    category TEXT NOT NULL DEFAULT 'general',
    related_terms JSONB DEFAULT '[]'::jsonb,
    examples JSONB DEFAULT '[]'::jsonb,
    source TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.dsl_entries ENABLE ROW LEVEL SECURITY;

-- Allow public read
DROP POLICY IF EXISTS "Public read dsl_entries" ON public.dsl_entries;
CREATE POLICY "Public read dsl_entries" ON public.dsl_entries
    FOR SELECT USING (true);

-- Allow public insert/update/delete
DROP POLICY IF EXISTS "Public all dsl_entries" ON public.dsl_entries;
CREATE POLICY "Public all dsl_entries" ON public.dsl_entries
    FOR ALL USING (true) WITH CHECK (true);

-- ── SEED DATA ──────────────────────────────────────────────────────────────

INSERT INTO public.dsl_entries (term, definition, context, category, related_terms, examples, source) VALUES

-- ── Framework Category ─────────────────────────────────────────────────────
(
    '7-Stage Framework',
    'The core structural methodology that organises all project work into seven sequential stages: Real Unknown → Environment → Simulation → Formula → Symbols → Semblance → Testing Known. Each stage maps to a cognitive learning step from active ignorance through to consolidation.',
    'Used across the entire project to classify files, structure directories, plan work, and audit progress. Referenced in agent guides, navigation, and README files.',
    'framework',
    '["Delivery Pilot", "Stage Gates", "Cognitive Mapping", "Active Ignorance", "Consolidation"]',
    '["1_Real_Unknown/ stores problem statements and OKRs (Stage 1)", "5_Symbols/ contains all executable code (Stage 5)", "6_Semblance/ holds error logs and hotfixes (Stage 6)"]',
    'Delivery Pilot Architecture'
),
(
    'Delivery Pilot',
    'The overarching AI-driven project orchestration template that guides developers (human and AI agents) through a structured, disciplined development lifecycle from initial problem definition to final verified deployment.',
    'Referenced in agent guides (claude.md, gemini.md), architecture docs, and project READMEs as the meta-framework for how work is organised.',
    'framework',
    '["7-Stage Framework", "Self-Learning Platform", "AI Agent", "Orchestration"]',
    '["claude.md explains how Claude should use the Delivery Pilot to complete tasks", "4_Formula/delivery_pilot/ contains the pilot''s core documentation"]',
    'Delivery Pilot Architecture'
),
(
    'Self-Learning Platform',
    'A system engineered to capture execution history, mistakes, reasoning, and lessons learned. The primary goal is to turn temporary developer interactions into permanent, reusable knowledge loops.',
    'Referenced in project philosophy documents, agent guides, and the membership value proposition. Drives the requirement for detailed logging and reflection.',
    'framework',
    '["Active Reflection Routine", "LLM Thinking Log", "Lessons Learned", "6_Semblance"]',
    '["Every milestone triggers a lessons_learned.md entry in 6_Semblance/", "LLM Thinking Log captures every decision driver during task execution"]',
    'Delivery Pilot Documentation'
),
(
    'Cognitive Mapping',
    'The mapping of each of the 7 stages to a specific cognitive/learning step: Active Ignorance (Stage 1), Mental Sandbox-Context (Stage 2), Mental Sandbox-Vision (Stage 3), Synthesis (Stage 4), Execution (Stage 5), Feedback Loop (Stage 6), Consolidation (Stage 7).',
    'Used in architecture documentation, DSL glossary, and agent training to explain the pedagogical rationale behind the 7-stage structure.',
    'framework',
    '["7-Stage Framework", "Active Ignorance", "Consolidation", "Synthesis"]',
    '["Stage 1 = Active Ignorance: explicitly stating what you do not know before coding", "Stage 7 = Consolidation: proving unknowns are now known via test outcomes"]',
    'DSL Glossary (4_Formula/delivery_pilot/dsl.md)'
),

-- ── Architecture Category ──────────────────────────────────────────────────
(
    'Two-Menu Architecture',
    'A navigation design split that separates audience visibility: the Project Menu (custom user-facing links to app features, always visible) and the Debug Menu (internal system navigation linking to the 7 stages and developer guides, toggled via a fixed bottom-right button and persisted via cookie).',
    'Implemented in nav.js, navigation_config.json, and every HTML page. The debug panel toggle is at the bottom-right of every page.',
    'architecture',
    '["Project Menu", "Debug Menu", "Navigation Config", "nav.js"]',
    '["Project Menu shows Preprod → Production → Post Prod → Timeline → Pipeline", "Debug Menu shows all 7 stage folders with their files"]',
    'Navigation System (2_Environment/9_navigation.md)'
),
(
    'Stage Gates',
    'Quality checkpoints between major phases (Pre-Prod → Production → Post-Prod) that require passing a sanity checklist before proceeding. Each gate ensures all artefacts from the previous stage are complete and validated.',
    'Referenced in the Sanity Checklist page, producer checklist, and pipeline visualisation. The gate check is enforced by the producer_checklist.html and sanity_checklist.html pages.',
    'architecture',
    '["Sanity Checklist", "Producer Checklist", "Pipeline", "Stage Gates"]',
    '["Pre-Prod gate requires: problem validated, research complete, script written, assets created", "Production gate requires: all scenes recorded, footage mapped, checklist signed off"]',
    'Sanity Checklist (5_Symbols/sanity_checklist.html)'
),
(
    'Active Reflection Routine',
    'The requirement for both humans and AI agents to compile retrospective logs inside 6_Semblance/logs/lessons_learned.md immediately following the completion of any project milestone.',
    'Mandated in agent guides (claude.md, gemini.md) and enforced by the Self-Learning Platform philosophy.',
    'architecture',
    '["Self-Learning Platform", "Lessons Learned", "6_Semblance", "LLM Thinking Log"]',
    '["After completing M1 recording, write lessons_learned.md entry", "After fixing CI pipeline, document the root cause and fix in lessons_learned.md"]',
    'Delivery Pilot Documentation'
),

-- ── Production Category ────────────────────────────────────────────────────
(
    'EDL (Edit Design List)',
    'A per-scene timing and transition specification that describes exactly how each visual and audio element should be assembled in post-production. Each EDL entry includes timing, description, and sort order.',
    'Used in the production_shotlist.html page where editors define scene-level assembly instructions. Stored in the edl_entries Supabase table.',
    'production',
    '["Scenes", "Shot List", "Post-Production", "Cues"]',
    '["Scene 1.1 EDL: 0:00-0:15 establishing shot, 0:15-0:45 talking head overlay", "Each EDL entry has timing (e.g., 0:00-0:10), description, and sort_order"]',
    'Production Shotlist (5_Symbols/production/postprod/production_shotlist.html)'
),
(
    'Lower Thirds',
    'Graphic overlays placed in the lower portion of the video frame that display the speaker name, title, or contextual label. They are keyed by background image and composed with CSS in the production pipeline.',
    'Managed in the lower_thirds.html page, stored as scene metadata (lt_image, lt_main, lt_sub, overlay_lt columns in the scenes table).',
    'production',
    '["Scenes", "Overlay", "Post-Production", "Talking Head"]',
    '["Main title: Architecture Overview, Subtitle: Module 1, Section 1", "Lower third image is a transparent PNG composited over the background"]',
    'Lower Thirds Manager (5_Symbols/production/postprod/lower_thirds.html)'
),
(
    'IVQ (Interactive Video Quiz)',
    'An interactive quiz system embedded into course videos that tests viewer comprehension at key points. Questions can be multiple-choice or open-ended.',
    'Built as a standalone HTML app (ivq.html) at both preprod and top level. Questions are stored in a Supabase table and linked to specific videos.',
    'production',
    '["Course Content", "Video Module", "Quiz", "Knowledge Check"]',
    '["IVQ appears at the end of each video module", "Questions are fetched from Supabase ivq_questions table by video_id"]',
    'IVQ Manager (5_Symbols/production/preprod/ivq.html)'
),

-- ── Infrastructure Category ────────────────────────────────────────────────
(
    'Azure Blob Storage',
    'The primary cloud object storage for all research media assets (images, audio, videos, notes). Operates behind the Go server proxy which generates short-lived SAS tokens for each operation — credentials never reach the browser.',
    'Used in all research pages (images.html, audio.html, videos.html, notes.html) via the /api/research/* endpoints. Credentials stored in Azure Key Vault.',
    'infrastructure',
    '["Azure Key Vault", "SAS Token", "Go Server Proxy", "AZURE_STORAGE_CONN_STR"]',
    '["research-images container holds all reference images", "notes.html POSTs to /api/research/upload?container=research-notes to save markdown"]',
    'Research Hub (5_Symbols/production/preprod/research/)'
),
(
    'Supabase',
    'The PostgreSQL-backed backend-as-a-service used for structured data: course modules, videos, scenes, scripts, sentences, IVQs, DSL entries, and more. Accessed via the anon public key from the browser for read/write.',
    'Used across virtually every data-driven page. The Supabase client initialises with the project URL and anon key. RLS policies control public access.',
    'infrastructure',
    '["RLS (Row-Level Security)", "PostgreSQL", "Anon Key", "Supabase Client"]',
    '["course_modules table stores the course outline", "dsl_entries table stores DSL terms and definitions", "RLS policies allow public SELECT on all course content tables"]',
    'Database Schema (5_Symbols/supabase/schema/)'
),
(
    'Fly.io',
    'The hosting platform for the Go server that powers API endpoints, serves the research hub, and handles SAS token generation. Configured with auto-stop machines to minimise cost when idle.',
    'Referenced in deployment configs, CI/CD pipelines, and architecture documentation. The Go binary is deployed as a single Docker container.',
    'infrastructure',
    '["Go Server", "Docker", "Auto-stop", "Deployment"]',
    '["fly deploy deploys the latest Go binary", "Auto-stop machines spin down after 5 minutes of inactivity, saving ~$2/month"]',
    'Fly.io Setup (2_Environment/4_fly_io.md)'
),
(
    'SAS Token (Shared Access Signature)',
    'A short-lived (5-minute TTL) URI that grants restricted access to Azure Blob Storage resources. Generated server-side by the Go proxy — never exposed to the browser.',
    'Used transparently by all /api/research/* endpoints. The browser never sees the SAS token; the Go server proxies all blob operations.',
    'infrastructure',
    '["Azure Blob Storage", "Go Server Proxy", "AZURE_STORAGE_CONN_STR", "Azure Key Vault"]',
    '["GET /api/research/file?container=research-images&name=diagram.png creates a SAS URL internally", "SAS tokens expire after 5 minutes, limiting exposure if leaked"]',
    'Azure Storage Architecture'
),

-- ── Agent Category ─────────────────────────────────────────────────────────
(
    'AI Agent',
    'An LLM-powered autonomous assistant (Claude, Gemini, GitHub Copilot, Kilo Code, Kimi) configured with role-specific guides, tool access, and behavioural rules to execute project tasks within the Delivery Pilot framework.',
    'Each agent has a dedicated guide file at the repo root (claude.md, gemini.md, etc.) defining its purpose, skills, and constraints.',
    'agent',
    '["Delivery Pilot", "Agent Guide", "LLM", "Tool Access"]',
    '["Claude: full-stack dev, DevOps, 7-stage framework expertise", "Gemini: multimodal analysis, image generation", "Kimi: long-context code reasoning and synthesis"]',
    'Agent Guides (agents.md, claude.md, gemini.md, kilocode.md, kimi.md, copilot.md)'
),
(
    'LLM Thinking Log',
    'An explicit documentation process capturing the internal reasoning phase, evaluation steps, and decision drivers of an AI agent during task execution. Stored in 4_Formula/llm_thinking_log.md.',
    'Mandated before writing any code in 5_Symbols/. Agents must document their approach in the thinking log before implementation.',
    'agent',
    '["Active Reflection Routine", "Agent Guide", "Thinking Gate", "Decision Drivers"]',
    '["Before creating DSL page, agent documents: what tables, what columns, page layout, navigation update", "After implementation, agent reflects on what worked and what didn''t"]',
    'Delivery Pilot Documentation'
),

-- ── Content Category ────────────────────────────────────────────────────────
(
    'Talking Head',
    'A video format where the instructor appears on screen speaking directly to the camera, typically with a lower-third graphic overlay showing their name and topic.',
    'Used in script generation (sentences table has visual_mode = ''talking_head''), shot list scene type, and video production planning.',
    'content',
    '["Screenshare", "B-Roll", "Lower Thirds", "Scene Type"]',
    '["Module 1 Section 1 uses talking head format for the introduction", "Talking head scenes have a background image and lower third overlay"]',
    'Script Template (4_Formula/production/script.md)'
),
(
    'Screenshare',
    'A video format where the instructor shares their screen to demonstrate a technical concept, tool usage, or code walkthrough.',
    'Referenced in script sentences with visual_mode = ''screenshare'', used in production shot list for scene type designation.',
    'content',
    '["Talking Head", "B-Roll", "Scene Type", "Demo"]',
    '["Module 1 Section 2 demonstrates MCP server setup via screenshare", "Screenshare scenes include cursor movements and terminal interactions"]',
    'Script Template (4_Formula/production/script.md)'
),

-- ── Storage / Data Category ─────────────────────────────────────────────────
(
    'RLS (Row-Level Security)',
    'PostgreSQL security feature in Supabase that restricts which rows users can read, insert, update, or delete. Most tables use simple public-read policies (anon SELECT true) while write operations have per-table policies.',
    'Defined in every schema SQL file. Policies are critical for the anon key client pattern used in the browser.',
    'data',
    '["Supabase", "Anon Key", "Policy", "PostgreSQL"]',
    '["anon_select_modules: allows public SELECT on modules table", "anon_insert_checklist_progress: allows public INSERT into checklist_progress"]',
    'Core Schema (5_Symbols/supabase/schema/01_core_schema.sql)'
),
(
    'Symbols',
    'The literal representations of code execution — variables, classes, modules, Docker containers, and infrastructure configs that build the final application state. Maps to Stage 5 of the 7-Stage Framework.',
    'Used to refer to the 5_Symbols/ directory and all executable code within it. The term comes from semiotics: symbols are the tangible representations of abstract ideas.',
    'data',
    '["7-Stage Framework", "5_Symbols", "Execution Stage", "Semblance"]',
    '["5_Symbols/course_src/mcp-server/ - the MCP server implementation", "5_Symbols/production/ - all production HTML pages and assets"]',
    'DSL Glossary (4_Formula/delivery_pilot/dsl.md)'
),
(
    'Semblance',
    'The state representing the difference or gap between the theoretical plan (the Formula) and practical reality (unexpected exceptions, hotfixes, and workarounds). Maps to Stage 6 of the 7-Stage Framework.',
    'Used to refer to the 6_Semblance/ directory which stores error logs, fix logs, lessons learned, and gap analysis documents.',
    'data',
    '["7-Stage Framework", "6_Semblance", "Feedback Loop", "Symbols", "Gap Analysis"]',
    '["6_Semblance/errors/ stores detailed error analysis pages", "6_Semblance/logs/error.log is the raw runtime error stream"]',
    'DSL Glossary (4_Formula/delivery_pilot/dsl.md)'
),
(
    'Azure Key Vault',
    'The designated cloud credentials vault used to store, manage, and dynamically retrieve development secrets at runtime, enforcing zero secret leakage in version control. Holds AZURE_STORAGE_CONN_STR, SUPABASE_SERVICE_KEY, and Axiom tokens.',
    'Referenced in architecture docs, deployment configs, and the Go server startup sequence. Secrets are injected as environment variables at deployment time.',
    'data',
    '["AZURE_STORAGE_CONN_STR", "Go Server Proxy", "Secrets Management", "Fly.io Secrets"]',
    '["dp-kv-deliverypilot vault stores the Azure Storage connection string", "Go server reads AZURE_STORAGE_CONN_STR from environment at startup"]',
    'Azure Setup (2_Environment/5_setup_azure.md)'
);
