-- =============================================================================
-- Seed: greenscreen_backgrounds — one background-video plan per course video
-- Generated from course_videos (5 modules x 3 videos). Idempotent upsert.
-- Run AFTER migration_greenscreen_backgrounds.sql in the Supabase SQL Editor.
-- =============================================================================

INSERT INTO public.greenscreen_backgrounds
  (module_number, video_number, generation_status, video_provider, prompt,
   duration_seconds, preset_style, camera_movement, rationale)
VALUES
  (1, 1, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "Architecture Overview" (Module 1 — Architecture & Orchestration). Scene: frosted glass panels, floating API request/response cards, soft violet and blue depth-of-field. Subtly evokes: Claude API anatomy: Messages API, streaming, tool use. Keep the centre clear for the presenter; gentle slow zoom in motion; seamless 12s loop, no text, no logos.', 12, 'glassmorphic', 'slow_zoom_in', 'glassmorphic style ties Module 1''s identity to "Architecture Overview"; slow zoom in keeps motion calm behind the host.'),
  (1, 2, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "Stateful Orchestration" (Module 1 — Architecture & Orchestration). Scene: frosted glass panels, floating API request/response cards, soft violet and blue depth-of-field. Subtly evokes: Loops vs stateless middleware boundaries. Keep the centre clear for the presenter; gentle slow zoom in motion; seamless 12s loop, no text, no logos.', 12, 'glassmorphic', 'slow_zoom_in', 'glassmorphic style ties Module 1''s identity to "Stateful Orchestration"; slow zoom in keeps motion calm behind the host.'),
  (1, 3, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "Production Wiring" (Module 1 — Architecture & Orchestration). Scene: frosted glass panels, floating API request/response cards, soft violet and blue depth-of-field. Subtly evokes: Connecting Claude to enterprise data sources. Keep the centre clear for the presenter; gentle slow zoom in motion; seamless 12s loop, no text, no logos.', 12, 'glassmorphic', 'slow_zoom_in', 'glassmorphic style ties Module 1''s identity to "Production Wiring"; slow zoom in keeps motion calm behind the host.'),
  (2, 1, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "MCP Fundamentals" (Module 2 — Model Context Protocol). Scene: technical blueprint grid, client-server schematic lines, cyan wireframe nodes on dark navy. Subtly evokes: What is MCP? Protocol architecture. Keep the centre clear for the presenter; gentle slow pan right motion; seamless 12s loop, no text, no logos.', 12, 'blueprint', 'slow_pan_right', 'blueprint style ties Module 2''s identity to "MCP Fundamentals"; slow pan right keeps motion calm behind the host.'),
  (2, 2, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "Building an MCP Server" (Module 2 — Model Context Protocol). Scene: technical blueprint grid, client-server schematic lines, cyan wireframe nodes on dark navy. Subtly evokes: SQLite data bridge implementation. Keep the centre clear for the presenter; gentle slow pan right motion; seamless 12s loop, no text, no logos.', 12, 'blueprint', 'slow_pan_right', 'blueprint style ties Module 2''s identity to "Building an MCP Server"; slow pan right keeps motion calm behind the host.'),
  (2, 3, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "Enterprise MCP" (Module 2 — Model Context Protocol). Scene: technical blueprint grid, client-server schematic lines, cyan wireframe nodes on dark navy. Subtly evokes: Authentication and authorization boundaries. Keep the centre clear for the presenter; gentle slow pan right motion; seamless 12s loop, no text, no logos.', 12, 'blueprint', 'slow_pan_right', 'blueprint style ties Module 2''s identity to "Enterprise MCP"; slow pan right keeps motion calm behind the host.'),
  (3, 1, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "ZDR Principles" (Module 3 — Zero Data Retention & Security). Scene: moody tech-noir vault, VPC PrivateLink conduits, amber security indicators in low-key lighting. Subtly evokes: Why zero-data retention matters for enterprises. Keep the centre clear for the presenter; gentle orbit left motion; seamless 12s loop, no text, no logos.', 12, 'tech_noir', 'orbit_left', 'tech_noir style ties Module 3''s identity to "ZDR Principles"; orbit left keeps motion calm behind the host.'),
  (3, 2, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "Implementing ZDR" (Module 3 — Zero Data Retention & Security). Scene: moody tech-noir vault, VPC PrivateLink conduits, amber security indicators in low-key lighting. Subtly evokes: Terraform blueprint for VPC Interface Endpoints. Keep the centre clear for the presenter; gentle orbit left motion; seamless 12s loop, no text, no logos.', 12, 'tech_noir', 'orbit_left', 'tech_noir style ties Module 3''s identity to "Implementing ZDR"; orbit left keeps motion calm behind the host.'),
  (3, 3, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "ZDR in Production" (Module 3 — Zero Data Retention & Security). Scene: moody tech-noir vault, VPC PrivateLink conduits, amber security indicators in low-key lighting. Subtly evokes: Testing and verifying data retention boundaries. Keep the centre clear for the presenter; gentle orbit left motion; seamless 12s loop, no text, no logos.', 12, 'tech_noir', 'orbit_left', 'tech_noir style ties Module 3''s identity to "ZDR in Production"; orbit left keeps motion calm behind the host.'),
  (4, 1, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "Router Architecture" (Module 4 — Multi-Agent Router). Scene: neon cyberpunk routing fabric, branching decision-tree pathways, magenta and teal signal flow. Subtly evokes: Why deterministic routing matters. Keep the centre clear for the presenter; gentle tilt down motion; seamless 12s loop, no text, no logos.', 12, 'cyberpunk', 'tilt_down', 'cyberpunk style ties Module 4''s identity to "Router Architecture"; tilt down keeps motion calm behind the host.'),
  (4, 2, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "Building the Router" (Module 4 — Multi-Agent Router). Scene: neon cyberpunk routing fabric, branching decision-tree pathways, magenta and teal signal flow. Subtly evokes: Python implementation with router.py. Keep the centre clear for the presenter; gentle tilt down motion; seamless 12s loop, no text, no logos.', 12, 'cyberpunk', 'tilt_down', 'cyberpunk style ties Module 4''s identity to "Building the Router"; tilt down keeps motion calm behind the host.'),
  (4, 3, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "Router in Production" (Module 4 — Multi-Agent Router). Scene: neon cyberpunk routing fabric, branching decision-tree pathways, magenta and teal signal flow. Subtly evokes: Load testing and performance benchmarks. Keep the centre clear for the presenter; gentle tilt down motion; seamless 12s loop, no text, no logos.', 12, 'cyberpunk', 'tilt_down', 'cyberpunk style ties Module 4''s identity to "Router in Production"; tilt down keeps motion calm behind the host.'),
  (5, 1, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "Cost Optimization Fundamentals" (Module 5 — Cost Optimization & Caching). Scene: clean minimal studio, subtle cache-prefix bars and rising ROI curve, soft green accents. Subtly evokes: Understanding Claude pricing: input vs output tokens. Keep the centre clear for the presenter; gentle static motion; seamless 12s loop, no text, no logos.', 12, 'clean_minimal', 'static', 'clean_minimal style ties Module 5''s identity to "Cost Optimization Fundamentals"; static keeps motion calm behind the host.'),
  (5, 2, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "Implementing Caching" (Module 5 — Cost Optimization & Caching). Scene: clean minimal studio, subtle cache-prefix bars and rising ROI curve, soft green accents. Subtly evokes: Explicit cache point placement strategies. Keep the centre clear for the presenter; gentle static motion; seamless 12s loop, no text, no logos.', 12, 'clean_minimal', 'static', 'clean_minimal style ties Module 5''s identity to "Implementing Caching"; static keeps motion calm behind the host.'),
  (5, 3, 'pending', 'runway', 'Looping greenscreen-friendly background video for a talking-head lesson on "Enterprise ROI" (Module 5 — Cost Optimization & Caching). Scene: clean minimal studio, subtle cache-prefix bars and rising ROI curve, soft green accents. Subtly evokes: Real-world cost reduction case study (90% savings). Keep the centre clear for the presenter; gentle static motion; seamless 12s loop, no text, no logos.', 12, 'clean_minimal', 'static', 'clean_minimal style ties Module 5''s identity to "Enterprise ROI"; static keeps motion calm behind the host.')
ON CONFLICT (module_number, video_number) DO UPDATE SET
  prompt          = EXCLUDED.prompt,
  preset_style    = EXCLUDED.preset_style,
  camera_movement = EXCLUDED.camera_movement,
  rationale       = EXCLUDED.rationale,
  updated_at      = NOW();
